#include "pch.h"
#include "global.h"


TransformConst	g_transform_data = {};
GlobalConst		g_global_data = {};
//LightInfoConst	g_light_data = {};

extern const char* RES_TYPE_STR[(UINT)RES_TYPE::END] =
{
	"MESHDATA",
	"MATERIAL",
	"PREFAB",
	"MESH",
	"TEXTURE",
	"SOUND",
	"ANIMATION3D",
	"ANIMATOR_CONTROLLER",
	"GRAPHICS_SHADER",
	"COMPUTE_SHADER"
};

extern const wchar_t* RES_TYPE_WSTR[(UINT)RES_TYPE::END] =
{
	L"MESHDATA",
	L"MATERIAL",
	L"PREFAB",
	L"MESH",
	L"TEXTURE",
	L"SOUND",
	L"ANIMATION3D",
	L"ANIMATOR_CONTROLLER",
	L"GRAPHICS_SHADER",
	L"COMPUTE_SHADER"
};


extern const char* COMPONENT_TYPE_STR[(UINT)COMPONENT_TYPE::END] =
{
	"TRANSFORM",
	"ANIMATOR2D",
	"ANIMATOR3D",
	"COLLIDER2D",
	"COLLIDER3D",
	"LIGHT2D",
	"LIGHT3D",
	"CAMERA",
	"SOCKET",
	"REFLECTIONCAPTURE",
	"MESHRENDER",
	"PARTICLESYSTEM",
	"TILEMAP",
	"LANDSCAPE",
	"SKYBOX",
	"DECAL",
	"TRAILRENDERER",
	"FONTRENDERER",
};

extern const wchar_t* COMPONENT_TYPE_WSTR[(UINT)COMPONENT_TYPE::END] =
{
	L"TRANSFORM",
	L"ANIMATOR2D",
	L"ANIMATOR3D",
	L"COLLIDER2D",
	L"COLLIDER3D",
	L"LIGHT2D",
	L"LIGHT3D",
	L"CAMERA",
	L"SOCKET",
	L"REFLECTIONCAPTURE",
	L"MESHRENDER",
	L"PARTICLESYSTEM",
	L"TILEMAP",
	L"LANDSCAPE",
	L"SKYBOX",
	L"DECAL",
	L"TRAILRENDERER",
	L"FONTRENDERER",
};
